Change back to the starting directory
scivision/iri90 pull request #2
Opened 2016-10-09 19:10 UTC by georgegeddes

I ran into a problem where a file I saved after using `runiri` ended up in the directory of pyiri90 instead of my actual working directory. This fixes it by moving back after executing IRI.

2016-10-10 01:04 UTC, meresmclr approved these changes

2016-10-10 01:10 UTC, meresmclr requested changes
It looks like the .asc files have been moved
data/ to pyiri90/data   which is fine

and also copied into
pyiri90/data/data

it seems like the second copy might be unintentional?

2016-10-10 01:19 UTC, georgegeddes commented
Oh, yeah that was definitely not intended.

2016-11-03 03:15 UTC, scienceopen commented
@georgegeddes I fixed some silly code that caused the path trouble. Maybe it will work for you now.

2016-11-03 03:15 UTC, closed without merging